In [1]:
import pandas as pd

In [2]:
df = pd.Series([100,200,300,400,500])
type(df)

pandas.core.series.Series

In [3]:
df

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [4]:
df = pd.Series([100,200,300,400,500], index=["Karan", "raj", "vishal", "raju" ,"ramesh"])

In [5]:
df

Karan     100
raj       200
vishal    300
raju      400
ramesh    500
dtype: int64

In [6]:
Student_info = {
    "Name" : ("Karan","Vishal","Rajesh","Arjun","Rahul","RajVeer"),
    "Roll.No" : (32,52,45,62,20,32),
    "Subject" : ("Python","Java","c","c++","Flask","Web Dev"),
    "Marks" : (89,45,32,95,78,56)
}

df = pd.DataFrame(Student_info)

In [7]:
df

      Name  Roll.No  Subject  Marks
0    Karan       32   Python     89
1   Vishal       52     Java     45
2   Rajesh       45        c     32
3    Arjun       62      c++     95
4    Rahul       20    Flask     78
5  RajVeer       32  Web Dev     56

In [8]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [9]:
df.columns

Index(['Name', 'Roll.No', 'Subject', 'Marks'], dtype='object')

In [10]:
# Creating DataFrame.

In [11]:
# From python list

Data = [["Karan",21,98],["Arjun",12,99],["Vishal",33,85],["Rajesh",14,78],["Rahul",15,68],["Kajal",26,63]]

df = pd.DataFrame(Data , columns=["Name","Roll.No","Marks"])

In [12]:
df

     Name  Roll.No  Marks
0   Karan       21     98
1   Arjun       12     99
2  Vishal       33     85
3  Rajesh       14     78
4   Rahul       15     68
5   Kajal       26     63

In [13]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [14]:
df.columns

Index(['Name', 'Roll.No', 'Marks'], dtype='object')

In [15]:
# From Dictionary List.

data = {"Karan" : [10,20,30],"Arjun" : [40,50,60]}

df = pd.DataFrame(data)

In [16]:
df

   Karan  Arjun
0     10     40
1     20     50
2     30     60

In [17]:
df

   Karan  Arjun
0     10     40
1     20     50
2     30     60

In [18]:
df = pd.read_excel("Data.xlsx")

In [19]:
df

     Name  School  Marks Section  Roll.No
0   Karan     DAV     98       A       23
1   Vishal    BTA     95       B       20
2    Arjun   DEFF     96       A       21
3  Avinash    BTS     91       A       52
4    Rahul   Deff     56       B       65
5   Ramesh    SCP     34       B       42
6    Kunal    DPS     41       B       23
7   Roshan    BNT     45       A       59

In [20]:
df.head()  # First Five Data.

     Name  School  Marks Section  Roll.No
0   Karan     DAV     98       A       23
1   Vishal    BTA     95       B       20
2    Arjun   DEFF     96       A       21
3  Avinash    BTS     91       A       52
4    Rahul   Deff     56       B       65

In [21]:
df.tail() # last five Data.

     Name  School  Marks Section  Roll.No
3  Avinash    BTS     91       A       52
4    Rahul   Deff     56       B       65
5   Ramesh    SCP     34       B       42
6    Kunal    DPS     41       B       23
7   Roshan    BNT     45       A       59

In [22]:
df = pd.read_csv("Data.csv")

In [23]:
df

     Name  School  Marks
0   Karan     DAV     98
1   Vishal    BTA     95
2    Arjun   DEFF     96
3  Avinash    BTS     91

In [24]:
df = pd.read_json("Data.json")

In [25]:
df

     Name      lang
0   Karan    Python
1  Vishal      Java
2    Raju     Numpy
3   vijay  Power BI

In [26]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [27]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [28]:
# EDA (Exploratory Data Analysis).

In [29]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [30]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [32]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [33]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [34]:
df.shape

(244, 7)

In [35]:
df.nunique()

total_bill    229
tip           123
sex             2
smoker          2
day             4
time            2
size            6
dtype: int64

In [49]:
df.sample(5)

     total_bill   tip     sex smoker  day    time  size
186       20.90  3.50  Female    Yes  Sun  Dinner     3
90        28.97  3.00    Male    Yes  Fri  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
218        7.74  1.44    Male    Yes  Sat  Dinner     2
172        7.25  5.15    Male    Yes  Sun  Dinner     2