In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("student_health_data.csv")

In [3]:
df

,Student_ID,Age,Gender,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Stress_Level_Biosensor,Stress_Level_Self_Report,Physical_Activity,Sleep_Quality,Mood,Study_Hours,Project_Hours,Health_Risk_Level,Family_members
0,1,24,M,50.663217,122.173015,84.419860,3.137350,9.028669,High,Moderate,Happy,34.520973,16.800956,Moderate,2
1,2,21,F,57.926042,110.778407,75.696145,3.699078,5.819697,Moderate,Good,Stressed,16.763846,15.791154,Moderate,1
2,3,22,M,59.294219,109.375673,83.803814,6.785156,5.892360,Low,Moderate,Happy,44.203798,25.678437,Moderate,12
3,4,24,M,76.826232,125.142227,78.091587,6.408509,6.884001,High,Poor,Happy,21.776645,20.808391,High,9
4,5,20,M,68.342769,107.515592,80.674937,7.264719,4.483450,Moderate,Poor,Happy,8.964999,15.194045,Moderate,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,23,F,68.185217,126.031324,69.156288,8.318278,6.841725,Moderate,Moderate,Stressed,30.554113,9.491591,Moderate,7
996,997,18,F,77.720216,100.627116,75.569051,6.295881,4.152130,High,Poor,Happy,29.285850,22.819961,High,6
997,998,24,M,85.313237,124.362792,91.817614,2.896868,9.253887,Moderate,Good,Happy,15.330941,19.010784,Moderate,14
998,999,21,M,79.212477,106.370246,77.218808,3.130484,2.205774,Low,Poor,Neutral,31.921143,9.159565,Low,12
999,1000,23,F,64.576277,109.274277,76.628119,6.652274,7.043606,Moderate,Good,Happy,30.944070,20.068335,Moderate,4

In [4]:
df.head()

,Student_ID,Age,Gender,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Stress_Level_Biosensor,Stress_Level_Self_Report,Physical_Activity,Sleep_Quality,Mood,Study_Hours,Project_Hours,Health_Risk_Level,Family_members
0,1,24,M,50.663217,122.173015,84.419860,3.137350,9.028669,High,Moderate,Happy,34.520973,16.800956,Moderate,2
1,2,21,F,57.926042,110.778407,75.696145,3.699078,5.819697,Moderate,Good,Stressed,16.763846,15.791154,Moderate,1
2,3,22,M,59.294219,109.375673,83.803814,6.785156,5.892360,Low,Moderate,Happy,44.203798,25.678437,Moderate,12
3,4,24,M,76.826232,125.142227,78.091587,6.408509,6.884001,High,Poor,Happy,21.776645,20.808391,High,9
4,5,20,M,68.342769,107.515592,80.674937,7.264719,4.483450,Moderate,Poor,Happy,8.964999,15.194045,Moderate,7

In [5]:
# Selecting Columns.
df["Mood"]

0         Happy
1      Stressed
2         Happy
3         Happy
4         Happy
         ...
995    Stressed
996       Happy
997       Happy
998     Neutral
999       Happy
Name: Mood, Length: 1000, dtype: object

In [6]:
# Selecting Row.
df.loc[1]
df.iloc[0]

Student_ID                           1
Age                                 24
Gender                               M
Heart_Rate                   50.663217
Blood_Pressure_Systolic     122.173015
Blood_Pressure_Diastolic      84.41986
Stress_Level_Biosensor         3.13735
Stress_Level_Self_Report      9.028669
Physical_Activity                 High
Sleep_Quality                 Moderate
Mood                             Happy
Study_Hours                  34.520973
Project_Hours                16.800956
Health_Risk_Level             Moderate
Family_members                       2
Name: 0, dtype: object

In [7]:
# Select Specific Rows and Columns.
df.loc[0,"Age"]
df.iloc[4,3]

np.float64(68.34276947)

In [8]:
# You can Also Sliceing.
df.loc[0:5, ["Student_ID","Physical_Activity"]]

   Student_ID Physical_Activity
0           1              High
1           2          Moderate
2           3               Low
3           4              High
4           5          Moderate
5           6          Moderate

In [9]:
#  Fast Access. .at And .iot

df.at[0,"Student_ID"]
df.iat[0,4]

np.float64(122.173015)

In [10]:
# Filtering with Conditions.

df[df["Age"]>18]  # Simple Conditions.

,Student_ID,Age,Gender,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Stress_Level_Biosensor,Stress_Level_Self_Report,Physical_Activity,Sleep_Quality,Mood,Study_Hours,Project_Hours,Health_Risk_Level,Family_members
0,1,24,M,50.663217,122.173015,84.419860,3.137350,9.028669,High,Moderate,Happy,34.520973,16.800956,Moderate,2
1,2,21,F,57.926042,110.778407,75.696145,3.699078,5.819697,Moderate,Good,Stressed,16.763846,15.791154,Moderate,1
2,3,22,M,59.294219,109.375673,83.803814,6.785156,5.892360,Low,Moderate,Happy,44.203798,25.678437,Moderate,12
3,4,24,M,76.826232,125.142227,78.091587,6.408509,6.884001,High,Poor,Happy,21.776645,20.808391,High,9
4,5,20,M,68.342769,107.515592,80.674937,7.264719,4.483450,Moderate,Poor,Happy,8.964999,15.194045,Moderate,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,994,21,F,51.420080,132.956877,93.201842,7.589973,4.761993,Moderate,Poor,Neutral,41.475665,11.496868,Moderate,1
995,996,23,F,68.185217,126.031324,69.156288,8.318278,6.841725,Moderate,Moderate,Stressed,30.554113,9.491591,Moderate,7
997,998,24,M,85.313237,124.362792,91.817614,2.896868,9.253887,Moderate,Good,Happy,15.330941,19.010784,Moderate,14
998,999,21,M,79.212477,106.370246,77.218808,3.130484,2.205774,Low,Poor,Neutral,31.921143,9.159565,Low,12
999,1000,23,F,64.576277,109.274277,76.628119,6.652274,7.043606,Moderate,Good,Happy,30.944070,20.068335,Moderate,4

In [11]:
df[df["Age"]>21] ["Age"]  # Filtering only Age.

0      24
2      22
3      24
5      22
6      22
       ..
988    24
991    24
995    23
997    24
999    23
Name: Age, Length: 421, dtype: int64

In [12]:
# Filtering Student ID.

df[df["Student_ID"]>520]

,Student_ID,Age,Gender,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Stress_Level_Biosensor,Stress_Level_Self_Report,Physical_Activity,Sleep_Quality,Mood,Study_Hours,Project_Hours,Health_Risk_Level,Family_members
520,521,21,F,68.714925,121.046203,70.722159,6.247952,7.440964,Moderate,Good,Neutral,20.308493,19.644625,Moderate,8
521,522,22,M,79.893694,110.403532,77.606231,7.462128,8.093438,High,Moderate,Happy,30.242546,16.124754,High,1
522,523,19,M,64.928921,104.962921,77.866702,4.348392,7.336939,Low,Poor,Happy,25.711366,12.142747,Moderate,2
523,524,21,F,58.289581,103.473102,89.599567,1.832046,6.307561,Moderate,Poor,Happy,38.077257,19.830857,Moderate,3
524,525,19,F,82.078093,138.746711,95.834773,5.121103,5.049215,Moderate,Good,Neutral,37.879313,16.903779,Moderate,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,23,F,68.185217,126.031324,69.156288,8.318278,6.841725,Moderate,Moderate,Stressed,30.554113,9.491591,Moderate,7
996,997,18,F,77.720216,100.627116,75.569051,6.295881,4.152130,High,Poor,Happy,29.285850,22.819961,High,6
997,998,24,M,85.313237,124.362792,91.817614,2.896868,9.253887,Moderate,Good,Happy,15.330941,19.010784,Moderate,14
998,999,21,M,79.212477,106.370246,77.218808,3.130484,2.205774,Low,Poor,Neutral,31.921143,9.159565,Low,12
999,1000,23,F,64.576277,109.274277,76.628119,6.652274,7.043606,Moderate,Good,Happy,30.944070,20.068335,Moderate,4

In [13]:
# Multiple Conditions (AND/OR)

df[(df['Student_ID']>520) & (df['Blood_Pressure_Systolic']>123)]   # This is AND Conditions.

,Student_ID,Age,Gender,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Stress_Level_Biosensor,Stress_Level_Self_Report,Physical_Activity,Sleep_Quality,Mood,Study_Hours,Project_Hours,Health_Risk_Level,Family_members
524,525,19,F,82.078093,138.746711,95.834773,5.121103,5.049215,Moderate,Good,Neutral,37.879313,16.903779,Moderate,3
526,527,20,F,78.786435,138.266227,99.928326,8.803542,9.611521,High,Moderate,Happy,37.463831,15.436387,High,5
531,532,19,M,69.848069,133.979696,74.577177,4.132468,5.090345,Low,Moderate,Happy,38.108617,15.928583,Moderate,13
532,533,24,F,78.631002,147.200159,62.032620,9.060002,2.883590,High,Moderate,Neutral,37.235823,15.228147,Moderate,2
536,537,22,M,60.058938,128.115851,68.822503,5.734846,4.419640,High,Good,Neutral,29.853062,20.610662,Moderate,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,990,20,M,80.761463,160.270114,88.618168,1.067168,8.749079,High,Poor,Stressed,38.108637,12.299347,High,5
991,992,24,F,63.471032,129.910851,68.920170,7.462613,1.114808,Moderate,Moderate,Neutral,25.092080,19.915251,Moderate,11
993,994,21,F,51.420080,132.956877,93.201842,7.589973,4.761993,Moderate,Poor,Neutral,41.475665,11.496868,Moderate,1
995,996,23,F,68.185217,126.031324,69.156288,8.318278,6.841725,Moderate,Moderate,Stressed,30.554113,9.491591,Moderate,7
997,998,24,M,85.313237,124.362792,91.817614,2.896868,9.253887,Moderate,Good,Happy,15.330941,19.010784,Moderate,14

In [14]:
df[(df['Student_ID']>520) | (df['Blood_Pressure_Systolic']>123)]   # This is OR Conditions.

,Student_ID,Age,Gender,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Stress_Level_Biosensor,Stress_Level_Self_Report,Physical_Activity,Sleep_Quality,Mood,Study_Hours,Project_Hours,Health_Risk_Level,Family_members
3,4,24,M,76.826232,125.142227,78.091587,6.408509,6.884001,High,Poor,Happy,21.776645,20.808391,High,9
8,9,19,F,81.671029,142.820977,74.676877,5.221367,5.115074,Moderate,Moderate,Neutral,37.211195,8.854986,Moderate,8
10,11,24,F,54.300397,127.678861,81.161731,2.621428,8.990359,High,Moderate,Happy,24.772251,21.214005,Moderate,9
12,13,20,F,64.824663,138.396077,84.015606,8.953156,8.403831,Moderate,Good,Neutral,40.484849,12.992542,High,2
13,14,22,F,64.010756,137.356446,84.683156,4.086367,2.890426,Moderate,Moderate,Neutral,20.141895,12.627748,Low,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,23,F,68.185217,126.031324,69.156288,8.318278,6.841725,Moderate,Moderate,Stressed,30.554113,9.491591,Moderate,7
996,997,18,F,77.720216,100.627116,75.569051,6.295881,4.152130,High,Poor,Happy,29.285850,22.819961,High,6
997,998,24,M,85.313237,124.362792,91.817614,2.896868,9.253887,Moderate,Good,Happy,15.330941,19.010784,Moderate,14
998,999,21,M,79.212477,106.370246,77.218808,3.130484,2.205774,Low,Poor,Neutral,31.921143,9.159565,Low,12
999,1000,23,F,64.576277,109.274277,76.628119,6.652274,7.043606,Moderate,Good,Happy,30.944070,20.068335,Moderate,4

In [21]:
# This is a cleaner, SQL- like way to filter.

df.query("Student_ID > 230")

,Student_ID,Age,Gender,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Stress_Level_Biosensor,Stress_Level_Self_Report,Physical_Activity,Sleep_Quality,Mood,Study_Hours,Project_Hours,Health_Risk_Level,Family_members
230,231,20,F,68.432696,116.606087,99.898551,3.991840,1.426741,High,Good,Neutral,44.844591,23.755678,Low,1
231,232,18,M,80.624015,131.340800,83.509425,3.839799,8.210544,Low,Moderate,Happy,16.852265,12.112989,Moderate,4
232,233,23,F,50.000000,119.016786,96.263804,1.959613,6.439426,Low,Poor,Happy,41.982760,17.064107,Moderate,8
233,234,22,F,72.351998,149.725377,74.973804,4.301185,2.786886,Moderate,Poor,Happy,29.821334,9.038182,Low,11
234,235,18,F,58.444320,143.531679,77.014033,1.895452,5.453456,Low,Moderate,Stressed,29.389027,10.355073,Moderate,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,23,F,68.185217,126.031324,69.156288,8.318278,6.841725,Moderate,Moderate,Stressed,30.554113,9.491591,Moderate,7
996,997,18,F,77.720216,100.627116,75.569051,6.295881,4.152130,High,Poor,Happy,29.285850,22.819961,High,6
997,998,24,M,85.313237,124.362792,91.817614,2.896868,9.253887,Moderate,Good,Happy,15.330941,19.010784,Moderate,14
998,999,21,M,79.212477,106.370246,77.218808,3.130484,2.205774,Low,Poor,Neutral,31.921143,9.159565,Low,12
999,1000,23,F,64.576277,109.274277,76.628119,6.652274,7.043606,Moderate,Good,Happy,30.944070,20.068335,Moderate,4

In [25]:
df.query("Student_ID > 970 and Heart_Rate > 68")

,Student_ID,Age,Gender,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Stress_Level_Biosensor,Stress_Level_Self_Report,Physical_Activity,Sleep_Quality,Mood,Study_Hours,Project_Hours,Health_Risk_Level,Family_members
970,971,24,M,74.520333,138.357798,81.634055,1.150044,8.886631,Low,Moderate,Neutral,36.558682,9.937628,Moderate,3
975,976,23,F,70.068683,118.878838,79.053762,3.880145,4.951263,Moderate,Poor,Neutral,36.352531,16.045849,Low,12
976,977,19,M,80.844796,90.000000,78.658444,5.554402,1.403929,Low,Poor,Neutral,26.357099,12.771241,Moderate,2
978,979,20,F,74.801461,113.633269,85.573043,9.637711,5.232666,High,Good,Stressed,39.016851,15.017524,Moderate,2
979,980,24,F,97.308672,135.537379,78.658548,8.664233,1.260971,High,Good,Happy,26.187293,13.899089,Moderate,3
980,981,23,M,73.773507,115.903165,84.034689,8.774107,7.208390,Moderate,Moderate,Neutral,14.075170,18.651249,High,8
981,982,21,M,68.195102,135.816475,74.506401,4.660964,5.336535,Low,Moderate,Stressed,43.194218,13.143603,Moderate,6
983,984,23,F,68.056685,90.535612,74.344887,2.294885,2.928446,Moderate,Moderate,Happy,26.972471,19.551258,Low,8
985,986,19,M,72.686614,125.174175,65.239329,1.179756,6.168642,High,Poor,Happy,28.495301,12.298142,High,2
986,987,19,F,71.035441,123.929255,76.195927,6.279416,6.598265,Moderate,Poor,Happy,35.205989,2.571681,Moderate,5
988,989,24,M,69.814420,114.732057,82.789918,5.662138,8.353919,High,Poor,Neutral,18.324809,10.806863,High,2
989,990,20,M,80.761463,160.270114,88.618168,1.067168,8.749079,High,Poor,Stressed,38.108637,12.299347,High,5
994,995,18,F,78.313493,106.615119,82.976049,3.097171,6.090017,Low,Moderate,Happy,22.847375,15.778271,Moderate,12
995,996,23,F,68.185217,126.031324,69.156288,8.318278,6.841725,Moderate,Moderate,Stressed,30.554113,9.491591,Moderate,7
996,997,18,F,77.720216,100.627116,75.569051,6.295881,4.152130,High,Poor,Happy,29.285850,22.819961,High,6
997,998,24,M,85.313237,124.362792,91.817614,2.896868,9.253887,Moderate,Good,Happy,15.330941,19.010784,Moderate,14
998,999,21,M,79.212477,106.370246,77.218808,3.130484,2.205774,Low,Poor,Neutral,31.921143,9.159565,Low,12